### ISSUE TITLE
Help a noob

### ISSUE THREAD

**Issue by DevStefan** [KiboOst/php-devoloDHC#2]
Hi KiboOst,
just tried to figure out, how i can use your code.
Have installed an apache-server on a raspi.
php : PHP Version 5.4.45-0+deb7u8
curl: 7.26.0 
got the code into phpDevoloAPI.php on the server
Startet this code
##############################################
```
<?php
echo "Test<br>";
require('inc/phpDevoloAPI.php');

//DHC login details
$login = "DevStefan@gmx.de";
$password = "MyDHCPassword";

$DHC = new DevoloDHC($login, $password);
if (isset($DHC->error)) echo $DHC->error;

//get some infos on your Devolo Home Control box:
echo "__infos__<br>";
$infos = $DHC->getInfos();
echo "<pre>".json_encode($infos['result'], JSON_PRETTY_PRINT)."</pre><br>";

?>
```
##########################################################
and got this answer:
Testzugriff
Couldn't find Devolo gateway.__infos__

null

**Comment by KiboOst** [comment]
Hi,
When you are on your web interface, do you still have the demo central first, then yours on the right ?
If so, try $DHC = new DevoloDHC($login, $password, true, 1);

Else, be sure you are using correct login/password ?

**Comment by DevStefan** [comment]
Thx for fast reply !
Yes, have the 2 options ( demo and to the right: my def )
First tried the line ...,true,1); then i made a new password. Login in webinterface ok, cant get in with php.
Still get the message a.m.
Do you have another idea or can I give you more input ?

**Comment by KiboOst** [comment]
ok, so use ...,true,1) to get the second central on the right.
I don't see what could happens, it seems to connect to the server but can't access the central.
Is there any strange character in your login or password ?

Could you try:
echo json_encode($DHC, JSON_PRETTY_PRINT);
And see what are the variables ?

**Comment by DevStefan** [comment]
Dear KiboOst, we got it.
I changed the password again because you ask for a special char: used $ or & in the both old passwords....
So I#m on the way to dig in the possibilities :)
Thx !

**Comment by KiboOst** [comment]
Ah! Thanks, will change mine to fix that!

**Comment by KiboOst** [comment]
Ok, I tested with $ and & and all works fine.
But, $ is a variable declaration in php, so if you write your password in double quote (") it will try to get this variable, and of course fail.
For example, $password = "my$pass" will fail or will add $pass variable to 'my' if it exist, but $password = 'my$pass' will work.
In short, in "double quote" php interpret the string and try to get a variable due to $, in 'simple quote', it just get the string without trying interpreting it.

Regards

**Comment by DevStefan** [comment]
Checked it with 'simple qoute' and & and $ . Lot of change-mails by the way :)
Runs then without problems. 
BR Stefan
