### ISSUE TITLE
Switch not changing state

### ISSUE THREAD

**Issue by ramsnerm** [KiboOst/php-devoloDHC#4]
So first of all thanks for your great API. I use it because the Devolo Home Control is not supporting all my cases and your API gives me the chance to integrate the non Devolo devices into other HA systems.

Currently I have an issue - I think it is related to Devolo Home Control itself but I wanted to ask you if you maybe have an idea or a solution with your API.

I included a Qubino relay 1D flush switch which works perfect ... until:
When I reset the device attach a temperature sensor and include it again (after I excluded it correctly) devolo sets the device up gives me a switch and shows the temperature - so everything right but if I change the switch state either with your API or with the Devolo Home Control the relay is not switch either On nor Off.

The Device data are as follows:

`<pre>Device:<br>{
    "result": {
        "items": [
            {
                "UID": "hdm:ZWave:EADFD80F\/31",
                "objectClass": [
                    "com.devolo.fi.widget.DeviceWidget",
                    "com.devolo.fi.widget.BaseWidget",
                    "com.devolo.fi.widget.Widget",
                    "com.devolo.fi.async.base.AsyncFunctionalItem",
                    "com.prosyst.mbs.services.fim.FunctionalItem"
                ],
                "attributes": [],
                "properties": {
                    "isOwn": true,
                    "operationStatus": null,
                    "wrongDevicePaired": false,
                    "deviceModelUID": "devolo.model.Unknown:Device",
                    "settingUIDs": [
                        "gds.hdm:ZWave:EADFD80F\/31"
                    ],
                    "isSecurelyIncluded": false,
                    "statisticsUID": "st.hdm:ZWave:EADFD80F\/31",
                    "icon": "icon_32",
                    "description": null,
                    "prodID": "0x0053",
                    "prodTypeID": "0x0002",
                    "secureInclusionCode": 0,
                    "itemName": "Toranlage",
                    "pendingOperations": null,
                    "zone": "Werkstatt\/Garage",
                    "elementUIDs": [
                        "devolo.BinarySwitch:hdm:ZWave:EADFD80F\/31#1",
                        "devolo.MultiLevelSensor:hdm:ZWave:EADFD80F\/31#2"
                    ],
                    "manID": "0x0159",
                    "zoneId": "hz_2",
                    "batteryLow": false,
                    "status": 2,
                    "batteryLevel": -1
                },
                "tags": []
            }
        ]
    },
    "id": 5,
    "jsonrpc": "2.0"
}</pre><br><pre>elementUIDs:<br>{
    "result": {
        "items": [
            {
                "UID": "devolo.BinarySwitch:hdm:ZWave:EADFD80F\/31#1",
                "objectClass": [
                    "com.devolo.fi.control.BinarySwitchFI",
                    "com.devolo.fi.widget.WidgetElement",
                    "com.devolo.fi.async.base.AsyncFunctionalItem",
                    "com.prosyst.mbs.services.fim.FunctionalItem"
                ],
                "attributes": [],
                "properties": {
                    "guiEnabled": true,
                    "itemId": null,
                    "operationStatus": {
                        "requestID": "180",
                        "name": "turnOn",
                        "functionalItemUID": "devolo.BinarySwitch:hdm:ZWave:EADFD80F\/31#1",
                        "status": 2,
                        "timestamp": 1505893899514
                    },
                    "pendingOperations": null,
                    "switchType": "normal",
                    "targetState": 1,
                    "state": 1,
                    "type": 1,
                    "widgetUID": "hdm:ZWave:EADFD80F\/31"
                },
                "tags": []
            },
            {
                "UID": "devolo.MultiLevelSensor:hdm:ZWave:EADFD80F\/31#2",
                "objectClass": [
                    "com.devolo.fi.label.MultiLevelSensorFI",
                    "com.devolo.fi.widget.WidgetElement",
                    "com.prosyst.mbs.services.fim.FunctionalItem"
                ],
                "attributes": [],
                "properties": {
                    "guiEnabled": true,
                    "itemId": null,
                    "sensorType": "temperature",
                    "type": 2,
                    "value": 12.9,
                    "widgetUID": "hdm:ZWave:EADFD80F\/31"
                },
                "tags": []
            }
        ]
    },
    "id": 6,
    "jsonrpc": "2.0"
}</pre><br><pre>settingUIDs:<br>{
    "result": {
        "items": [
            {
                "UID": "gds.hdm:ZWave:EADFD80F\/31",
                "objectClass": [
                    "com.devolo.fi.setting.GeneralDeviceSettings",
                    "com.devolo.fi.setting.DeviceSetting",
                    "com.prosyst.mbs.services.fim.FunctionalItem"
                ],
                "attributes": [],
                "properties": {
                    "settings": {
                        "eventsEnabled": true,
                        "name": "Toranlage",
                        "icon": "icon_32",
                        "zoneID": "hz_2"
                    },
                    "itemId": null
                },
                "tags": []
            }
        ]
    },
    "id": 7,
    "jsonrpc": "2.0"`

So my you have an idea or possibility, otherwise I have to detach the sensor. Many thanks in advance.

**Comment by KiboOst** [comment]
Hi ramsnerm,
Thanks for the kind words.

Regarding the qubinos, I can't do anything on my side. I have also a qubino 2 relays that does same thing, the wall switch doesn't get catch by Devolo and doesn't change state but it works.
Qubino shutters also works great, but never appear in diary and always show as not initialized. But they work, both in apps and API. And no qubino report consumption either...

I think this is because of such problems that the long overdue Devolo flush modules (qubinos ones) are still not on the market. We can only wait for Devolo updates to support them fully. At least 1 relay, shutter and dimmer should work flawlessly as these are the Devolo flush modules announced.

As soon as there is an update, I always check all API functions. Let's see...

**Comment by ramsnerm** [comment]
Thanks for the quick feedback - I had such a bad feeling about :-( Let's Home devolo makes its homework.

**Comment by ramsnerm** [comment]
Hi KiboOst,
I just added a small [CLI script](https://github.com/ramsnerm/php-devoloDHC-quibino-flush2relays) to handle the Qubino Flush 2 Relay with scenes, so I could use it in other home automation tools as single switches per relay. I am not a skilled software developer so I just decided to make a wrapper script instead of forking your API. Thanks for your inspiration!

**Comment by KiboOst** [comment]
Nice, I was thinking about adding support for the second switch in the API

**Comment by KiboOst** [comment]
Check v2.80: Qubino Flush 2 Relay ZMNHBDx support

**Comment by ramsnerm** [comment]
Hi @KiboOst,
I currently tested your new API Version 2.80 - everything is working perfectly. Now I will remove my CLI script repo :-) but I learned a bit more to work with Github.

**Comment by KiboOst** [comment]
No problem, new device is easy to support when I have them in hand ;-) 2 relay was on my todo list since I got one last week!
