### ISSUE TITLE
NodeJS port?

### ISSUE THREAD

**Issue by unm4sk1g** [KiboOst/php-devoloDHC#6]
Couldn't find a way to contact you directly, hopefully it's not a problem to post an issue about this.

Is it possible to port this to NodeJS? I've been trying, but no success in authorizing (cookies are messing up the stuff).

**Comment by KiboOst** [comment]
No problem to post here of course.

I don't know NodeJS, but have a look here:
https://github.com/kdietrich/node-devolo

**Comment by unm4sk1g** [comment]
It has some stuff I can't use here due to NodeJS version limitations. Anyways, here's what's currently not working for me. If I copy the JSESSIONID from browser (when logged in) and put it in gateways request, it works. But JSESSIONID that I get after POST (csrf, username and password), the gateways request throws me an HTML with 'You are using a browser that is not supported.'. I thought it was User-Agent that was causing this, but apparently it's not.

**Comment by unm4sk1g** [comment]
Resolved using request library, but this library helped alot also. Thanks :)
